FROM mysql:8.0

RUN mkdir -p /backups /nfs_shared

COPY scripts/backup.sh /backup.sh
RUN chmod +x /backup.sh

CMD ["/bin/bash", "-c", "while true; do /backup.sh; echo 'Next backup in 24h...'; sleep 86400; done"]